name: Python tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - AUTHORS.md
  pull_request:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
           options: "--check --verbose --diff"
           src: "./src"

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools_scm[toml] wheel setuptools
          python -m pip install --upgrade attrs types-attrs
          python -m pip install flake8 tox mypy
      - name: Mypy
        run: |
          mypy --cache-dir .mypy_cache --install-types --non-interactive ./src

  tests:
    runs-on: ${{ matrix.os }}
    needs: "mypy"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11.0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pytest
    - name: Test with pytest
      run: |
        pytest
    # - name: "Upload coverage to Codecov"
    #   uses: codecov/codecov-action@v3
    #   with:
    #     fail_ci_if_error: false
